/// Flutter icons AmatNow
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AmatNow
///      fonts:
///       - asset: fonts/AmatNow.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AmatNow {
  AmatNow._();

  static const _kFontFam = 'AmatNow';
  static const String? _kFontPkg = null;

  static const IconData thin_long_right = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bike = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_star = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shipping = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_agreement = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flutterwave = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stripe2 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin_alt = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pay_with_card = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alert = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key_password = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification_bell = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData recycle_bin = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scanner = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumb_up_alt = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_closed = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_open = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drawer_history = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drawer_support = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cash_hand = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_circle = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift_box = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData id_icon = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pickup_location = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData progress_icon = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData target_icon = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drawer_add_people = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drawer_bell = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drawer_discount = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drawer_people = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drawer_privacy = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drawer_profile = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData talk_support = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
